---
title: "Rscience - Anova - script01 - Anova - Import and control"
format: 
  html:
    css: custom_theme.css
    grid:
      body-width: 2000px
      margin-width: 250px
      gutter-width: 1.5rem
    toc: true
    toc-float: true
    toc-location: right
    self-contained: true
    link-citations: true # Util para ver referencias en el margen (ver `tufte.html` en la galería de Quarto)

knitr: 
    opts_chunk: 
        collapse: false
        comment: ""
params:
  clean_all: false
  special_echo: false     # R output
  special_include: false  # R code
---

<!-- HIDDEN - LIBRERIAS -->
```{r}
#| eval: true
#| echo: false
#| include: false
#| message: false
#| warning: false

library("knitr")
library("kableExtra")
library("tools")
library("DT")
library("htmltools")
```



<!-- HIDDEN - Loading local fn -->
```{r}
#| eval: true
#| echo: !expr params$special_echo
#| include: !expr params$special_include

folder_fn_local_relative <- "../zzz_fn_local"
folder_fn_local_absolute <- normalizePath(folder_fn_local_relative, mustWork = T)
vector_fn <- list.files(
  path = folder_fn_local_absolute, 
  pattern = "^fn_local.*\\.R$", 
  full.names = TRUE
)
vector_fn <- normalizePath(vector_fn, mustWork = T)

invisible(lapply(vector_fn, source, local = FALSE, encoding = "UTF-8"))
#lapply(vector_fn, source, local = FALSE, encoding = "UTF-8")
``` 



<!-- HIDDEN - Input folder (for RData files) -->
```{r}
#| eval: !expr params$special_include
#| echo: !expr params$special_echo
#| include: !expr params$special_include
#| results: asis



if(params$special_include) cat("# Input Folder: 'f02_quarto_mod", "\n")
if(params$special_include) cat("Esta carpeta contiene los archivos RData, los HTML y los QMD de codigo.", "\n")
```


```{r}
#| eval: true
#| echo: !expr params$special_echo
#| include: !expr params$special_include




# 1. Definir la carpeta base
input_folder01_relative <- file.path("..", "f02_quarto_mod")
input_folder01_absolute <- normalizePath(input_folder01_relative, mustWork = TRUE)
input_folder01_exists <- dir.exists(input_folder01_absolute)

cat("Input folder---------------------------------------------------------", "\n",
    "Relative path: ", input_folder01_relative, "\n",
    "Absolute path: ", input_folder01_absolute, "\n",
    "Folder exists:", input_folder01_exists, "\n",
    "---------------------------------------------------------------------------")


if(!input_folder01_exists) {
  cat("ERROR GRAVE - No se encontro la carpeta que debe contener a los archivos QMD y los archivos RData.",
      "Varifica si el nombre de la carpeta es el correcto o algun problema en el path de la carpeta.")
  knitr::knit_exit()
}
```


<!-- HIDDEN - LISTADO DE RDATA -->
```{r}
#| eval: !expr params$special_include
#| echo: !expr params$special_echo
#| include: !expr params$special_include
#| results: asis



if(params$special_include) cat("# RData files", "\n")
if(params$special_include) cat("Listamos los archivos RData que hay en la carpeta que los genera.", "\n")
```


```{r}
#| eval: true
#| echo: !expr params$special_echo
#| include: !expr params$special_include


vector_RData_file_path <- list.files(path = input_folder01_absolute, pattern = "\\.RData$", full.names = T)
vector_RData_file_path <- normalizePath(vector_RData_file_path, mustWork = TRUE)
vector_RData_file_exists <- file.exists(vector_RData_file_path)
vector_RData_file_name <- basename(vector_RData_file_path)
vector_RData_order <- 1:length(vector_RData_file_path)

df_RData <- data.frame(
  "order" = vector_RData_order,
  "file_name" = vector_RData_file_name,
  "file_exists" = vector_RData_file_exists,
  "file_path" = vector_RData_file_path)
df_RData

check_all_exists_RData <- all(vector_RData_file_exists)
phrase_check_yes_RData <- "All RData files exists." 
phrase_check_no_RData  <- "Not all RData files exists."
phrase_check_selected_RData <- ifelse(test = check_all_exists_RData, 
                                     yes = phrase_check_yes_RData, 
                                     no = phrase_check_no_RData)

cat(phrase_check_selected_RData)
cat("Check all RData: ", check_all_exists_RData, "\n")

if(!check_all_exists_RData) {
  cat("ERROR GRAVE 02 - No se encontraron en la carpeta alguno de los archivos RData.",
      "Varifica si el nombre de los archivos es correcto, o tal vez el path de la carpeta.")
  knitr::knit_exit()
}
```



```{r}
#| eval: true
#| echo: !expr params$special_echo
#| include: !expr params$special_include

# Supongamos que vector_RData_file_path ya existe
# Ejemplo: vector_RData_file_path <- c("data1.R", "data2.R")

# vector_RData_file_path contiene las rutas a tus archivos .RData

super_bag <- lapply(vector_RData_file_path, function(file_path) {
  
  # 1. Creamos un entorno nuevo para CADA archivo
  # Esto evita que si dos archivos tienen un objeto llamado 'plot_01', se borren entre sí.
  temp_env <- new.env()
  
  # 2. Normalizamos la ruta (importante en Linux/Windows)
  file_path_clean <- normalizePath(file_path, winslash = TRUE, mustWork = TRUE)
  
  # 3. Usamos LOAD especificando el entorno de destino
  # A diferencia de source(), load() no devuelve error de multibyte en binarios.
  load(file_path_clean, envir = temp_env)
  
  # 4. Convertimos el entorno a lista para que sea fácil de usar en Shiny
  return(as.list(temp_env))
})

# 5. Opcional: Ponemos nombres a los elementos de la lista según el archivo
names(super_bag) <- basename(vector_RData_file_path)

```


# Frases Level 02
```{r}
#| eval: true
#| echo: false
#| results: asis


aver02 <- super_bag[[6]]$vector_text_pack02

cat(aver02)
```



